// Package oapicodegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package oapicodegen

// Hello defines model for Hello.
type Hello struct {
	Message string `json:"message"`
}
